spring:
  application:
    name: data-extraction-service
  datasource:
    # url : jdbc:mysql://172.19.255.250:3306/intelligent-community?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    # driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://60.255.139.172:3306/intelligent-community-a?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qazZAQ!
    # type: com.alibaba.druid.pool.DruidDataSource
      # druid:
      # initial-size: 5
      # min-idle: 5
      # max-active: 20
      # max-wait: 60000
      # time-between-eviction-runs-millis: 60000
      # min-evictable-idle-time-millis: 300000
      # test-on-borrow: false
      # test-while-idle: true
      # test-on-return: false
      # validation-query: SELECT 1 FROM DUAL
      # filter:
      # stat:
      # log-slow-sql: true
    # filters: stat,wall,log4j

  jackson:
    serialization :
       indent-output : true

server:
  port: 8082
#mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.enc.domain.entity

####max server
mais:
  # server: http://172.19.255.251:3741
  server: http://60.255.139.164:3741
  user-name: admin
  password: ADMIN110
  project-id: JN01
  persion:
    url: /0-project/pictureFile
    data-img-url: /ms/persion-img/


####interface server
interface:
  server: http://60.255.139.167:8081

####订阅通知推送 IP 地址
# sube:
  # url: http://172.19.255.250:8082
sube:
  url: http://60.255.139.172:8082